apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBbFVzRzZDWWIwelNmRFBMcnZKWTRBekFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXhNVEkxTURrd01qVTVXaGNOTXpVeE1USXpNRGt3TWpVNVdqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUNzTGVyVXgzckhLWk1mbmQvTncvR3llNExzT0E5THhZVTJXCndZdnNlRXl2bzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk5ZWGd6a3Z2bEtDK0JNbgp5QVBsM0o3VmdONm1NQVVHQXl0bGNBTkJBRlkzU0VFWXZGakY5VStiRk0xbUFTL1pDWXRKakVFOXF0QTlkK2l1CmZSWnpwY3A1V0RjQXlPU3lwTXpzWUhZdVV6MGw5S3dpSkVzVlRnUmFVZlJHMFFjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1DNENBUUF3QlFZREsyVndCQ0lFSUk5VUZIa3BldmNpZkpPSDdxVWU5OHFlV0VWOXJJS0I2RnRjWnlXWnpkQ0EKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==
  token: {{ .Values.talosToken | b64enc }}
kind: Secret
metadata:
  name: talos
  namespace: {{ .Release.Namespace }}
type: Opaque
