apiVersion: v1
data:
  ca.crt: {{ .Values.talosCA | b64enc }}
  ca.key: {{ .Values.talosCAKey | b64enc }}
  tls.crt: {{ .Values.talosCert| b64enc }}
  tls.key: {{ .Values.talosKey | b64enc }}
  token: {{ .Values.talosToken | b64enc }}
kind: Secret
metadata:
  name: talos
  namespace: {{ .Release.Namespace }}
---
