apiVersion: v1
data:
  ca.crt: {{ .Values.talosCA }}
  ca.key: {{ .Values.talosCAKey }}
  tls.crt: {{ .Values.talosCert }}
  tls.key: {{ .Values.talosKey }}
  token: {{ .Values.talosToken }}
kind: Secret
metadata:
  name: talos
  namespace: {{ .Release.Namespace }}
---
